// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1FN1rY5PoQ7PzJnEQ4LxRTmKLMIglQ6Q',
    appId: '1:819431085135:web:a966a0c48af944100b063a',
    messagingSenderId: '819431085135',
    projectId: 'beanbrewapplication',
    authDomain: 'beanbrewapplication.firebaseapp.com',
    storageBucket: 'beanbrewapplication.appspot.com',
    measurementId: 'G-MGNWLME7TZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATuEoX9xxDMb7Lu1_q1qrTIFiC9F86xCY',
    appId: '1:819431085135:android:88ca97e65ce85d810b063a',
    messagingSenderId: '819431085135',
    projectId: 'beanbrewapplication',
    storageBucket: 'beanbrewapplication.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARAsleCLu1O0j7mRW9kF4daEr2DAO_wFY',
    appId: '1:819431085135:ios:a93b79c057d4b0c50b063a',
    messagingSenderId: '819431085135',
    projectId: 'beanbrewapplication',
    storageBucket: 'beanbrewapplication.appspot.com',
    iosBundleId: 'com.example.beanbrewapps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARAsleCLu1O0j7mRW9kF4daEr2DAO_wFY',
    appId: '1:819431085135:ios:a93b79c057d4b0c50b063a',
    messagingSenderId: '819431085135',
    projectId: 'beanbrewapplication',
    storageBucket: 'beanbrewapplication.appspot.com',
    iosBundleId: 'com.example.beanbrewapps',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1FN1rY5PoQ7PzJnEQ4LxRTmKLMIglQ6Q',
    appId: '1:819431085135:web:9a483c42866067b20b063a',
    messagingSenderId: '819431085135',
    projectId: 'beanbrewapplication',
    authDomain: 'beanbrewapplication.firebaseapp.com',
    storageBucket: 'beanbrewapplication.appspot.com',
    measurementId: 'G-VWG8L1EGGP',
  );
}
